# Generated by Django 3.2.7 on 2022-04-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
