# Generated by Django 3.2.7 on 2022-04-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_recommendation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
