# Generated by Django 3.2.7 on 2022-04-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_recommendation_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_recommendations',
            field=models.ManyToManyField(blank=True, related_name='old_recommendations', to='authentication.Recommendation'),
        ),
    ]
