# Generated by Django 3.2.7 on 2022-04-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_old_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='link',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
